manifest:
 remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.2 # set to desired version 
      import: app/west.yml
    - name: zmk-auto-layer
      remote: urob
      revision: v0.2 # set to same version as zmk above
  self:
    path: config
